language: objective-c
osx_image: xcode7.3
xcode_project: PSOperations.xcodeproj
xcode_sdk:
- iphonesimulator
- iphonesimulator
xcode_scheme:
- PSOperations
- PSOperationsAppForTests

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
